### ISSUE TITLE
Why are the two English letter keys like "g+n" not effective?

### ISSUE THREAD

**Issue by stitchDengg** [jamiebuilds/tinykeys#195]
```javascript
tinykeys(window, {
  "g+n": () => {
    console.log("g+n");
  },
});
``` 
it dose not work

**Comment by jamiebuilds** [comment]
Do you mean to write:

```ts
tinykeys(window, {
  "g n": () => {
    console.log("g n");
  },
});
```

Only modifier keys (`$mod`, `Control`, `Meta`, etc) can be appear before the `+`. This is for accessibility: 

Pressing multiple keys simultaneously is difficult for users with certain physical disabilities, which is why Windows/macOS/etc offer a feature called ["Sticky Keys"](https://en.wikipedia.org/wiki/Sticky_keys) for modifier keys, so that the user can press and release modifier keys and they will remain active until a non-modifier key is pressed.

Hence, with sticky keys on `Shift+N` can be typed: 

```rb
keydown(Shift) # active keys: [Shift]
keyup(Shift)   # active keys: [Shift]       <- Shift is active because of Sticky Keys
keydown(KeyN)  # active keys: [Shift, KeyN] <- Shift is active because of Sticky Keys
keyup(KeyN)    # active keys: []
```

But `G+N` cannot:

```rb
keydown(KeyG) # active keys: [KeyG]
keyup(KeyG)   # active keys: []
keydown(KeyN) # active keys: [KeyN]
keyup(KeyN)   # active keys: []
```
